### ISSUE TITLE
Search optimization in filterable-list-v2

### ISSUE THREAD

**Issue by Youngsiavash** [aman-maharshi/vanilla-js#1]
Hello dear friend.
There is something wrong in your filterable-list-v2. 
If you enter something into input field, the search method which you've implemented filters the links that just contains the user entered letters, without considering order of letters.
I made changes to solve the problem without any complicated tool in JS.

I just wanted to send a pull request but it appears I'm not able to do that.

**Comment by aman-maharshi** [comment]
Hi Siavash,
You're right it only checks if the word contains the letter or not without considering the precedence. I'll be happy to merge if u have any suggestions. Not sure how ur unable to send pull request. Let me know if u want me to do any changes on my end.

**Comment by Youngsiavash** [comment]
Dear Aman

It seems I'm not able to create a new branch on your project. Therefore, the pull request is not possible.
